# Copyright Contributors to the Opensynth-energy Project.
# SPDX-License-Identifier: Apache-2.0

import logging
from collections.abc import Generator
from datetime import date
from functools import cached_property
from typing import Literal, Tuple, cast

import numpy as np
import pandas as pd
import polars as pl
import torch
from tqdm.auto import tqdm

from opensynth.data_modules.lcl_data_module import LCLDataModule
from opensynth.models.faraday.model import FaradayModel
from opensynth.utils.polars import randomize_index_column, semiwide_to_wide

from .stitch import stitch_samples
from .utils import date_per_weekday_and_month, sample_number_is_sufficient

DEFAULT_YEAR = 2024

logger = logging.getLogger(__name__)


class StitchedFaradayModel:
    """Stitched Faraday model to generate longer time-series.

    First instantiate an StitchedFaradayModel instance, where `trained_model`
    is an instance of FaradayModel(), which is already trained.

    >>> model = StitchedFaradayModel(trained_model)

    Then, use the `generate_stitched_samples()` method to generate synthetic
    samples for a month or a year. Keep in mind that Faraday, as currently
    implemented, will not impose any constraints on the consistency between
    different days.

    >>> generated_samples = model.generate_stitched_samples(
            dm=dm,
            month=10,
            n_samples=10,
            year=2023,
            )
    """

    required_features = ["month", "dayofweek"]

    def __init__(self, fm: FaradayModel):
        self.model = fm

    @property
    def model(self):
        return self._model

    @model.setter
    def model(self, model: FaradayModel):
        is_valid_model = True
        for feature in self.required_features:
            if feature not in model.feature_list:
                logger.error(
                    f"Feature '{feature}' not present in trained model,"
                    " but this feature is needed for sampling."
                )
                is_valid_model = False

        if not is_valid_model:
            raise ValueError(
                "Please provide a model with the required features."
            )

        self._model = model

    @cached_property
    def optional_features(self) -> list[str]:
        """list with names of optional features"""
        return [
            f
            for f in self.model.feature_list
            if f not in self.required_features
        ]

    def generate_stitched_samples(
        self,
        dm: LCLDataModule,
        n_samples: int,
        month: int | None = None,
        year: int = DEFAULT_YEAR,
        period: Literal["month", "year"] = "month",
        fmt: Literal["pandas", "polars"] = "polars",
    ) -> pl.DataFrame | pd.DataFrame:
        """Generate DataFrame with Faraday samples for a month or year.

        Samples will be generated with all timesteps for all days in the
        specified month or year.

        Args:
            dm (LCLDataModule): Data module.
            n_samples (int): Number of synthetic samples to generate per month
                or year. This argument specifies the number of stitched-
                together samples. In practice, this means that more samples
                will be generated by the Faraday model. For instance, if
                generating samples for January, `n_samples` * 31 will be
                generated and stitched together to produce `n_samples` samples
                with 31 days.
            month (int): Specific month, used in combinatoon with
                `period="month"`.
            year (int, optional): Year to use for timestamps.
            period (str, optional): Generate samples for a full "month", or
                for a "year". Default is "month".
            fmt (str, optional): DataFrame format Either "pandas" or "polars",
                default is "polars".

        Returns:
            DataFrame in wide format with datetime as first columns.
        """
        match period:
            case "month":
                if month is None:
                    raise ValueError(
                        "The month needs to be specified "
                        "when period is 'month'"
                    )
                df = self._generate_full_synthetic_month(
                    dm=dm,
                    year=year,
                    month=month,
                    n_samples=n_samples,
                )
            case "year":
                df = self._generate_full_synthetic_year(
                    dm=dm, year=year, n_samples=n_samples
                )
            case _:
                raise ValueError(
                    "Invalid period, should be either 'month' or 'year'"
                )

        if fmt == "pandas":
            return df.to_pandas()

        return df

    def _get_sampled_features(
        self, dm: LCLDataModule, n_samples: int, year: int
    ) -> pl.DataFrame | None:
        """Generate DataFrame with sampled features.

        Generate samples and select the features.

        Args:
            dm (LCLDataModule): Data module.
            n_samples (int): Number of synthetic samples to generate per day.
            year (int, optional): Year to use for timestamps.

        Returns:
            DataFrame with sampled feature or None if there are no optional
                features.
        """
        features = self.optional_features
        if len(features) == 0:
            return None

        df = self._generate_synthetic_sample_df(
            dm, n_samples, year=year, month=1
        )
        sampled_features = (
            df.select(features)
            .group_by(features)
            .len()
            .rename({"len": "n_required"})
        )
        return sampled_features

    def _generate_sufficient_samples_for_month(
        self,
        dm: LCLDataModule,
        sampled_features: pl.DataFrame | None,
        year: int,
        month: int,
        n_samples: int,
        batch_size: int = 5000,
    ):
        """Generate DataFrame Faraday samples for a specific month.

        Samples will be generated with a timestamp that fits the specified
        month for each day in that month. Enough samples will be generated
        to ensure that for each of the selected combination of features at
        least one sample will be generated for each day.

        Args:
            dm (LCLDataModule): Data module.
            sampled_features (DataFrame or None): DataFrame with sampled
                combinations of features or None.
            year (int): Year to use for timestamps.
            month (int): Month (1-based) to use. If generated
                samples do not match the specified month, they will be
                discarded until enough samples are specified that do match.
            n_samples (int): Number of synthetic samples to generate for the
                specified month. This argument specifies the number of
                stitched-together samples. In practice, this means that more
                samples will be generated by the Faraday model. For instance,
                if generating samples for January, `n_samples` * 31 will be
                generated and stitched together to produce `n_samples` samples
                with 31 days.
            batch_size (int, optional): Batch size, default is 5000.

        Returns:
            DataFrame with generated samples.
        """

        # Initial batch of samples
        df = self._generate_synthetic_sample_df(
            dm, batch_size, year=year, month=month
        )

        while not sample_number_is_sufficient(
            df,
            n_samples,
            year,
            month,
            sampled_features,
        ):
            df = pl.concat(
                (
                    df,
                    self._generate_synthetic_sample_df(
                        dm=dm,
                        n_samples=batch_size,
                        year=year,
                        month=month,
                    ),
                )
            )

        return df

    def _generate_full_synthetic_month(
        self,
        dm,
        year: int,
        month: int,
        n_samples: int = 1,
        sampled_features: pl.DataFrame | None = None,
        randomize_index: bool = True,
    ) -> pl.DataFrame:
        """Generate DataFrame Faraday samples for a specific month.

        Samples will be generated with a timestamp that fits the specified
        month.

        Args:
            dm (LCLDataModule): Data module.
            year (int, optional): Year to use for timestamps.
            month (int, optional): Month (1-based) to use. If generated
                samples do not match the specified month, they will be
                discarded until enough samples are specified that do match.
            n_samples (int): Number of synthetic samples to generate for the
                specified month. This argument specifies the number of
                stitched-together samples. In practice, this means that more
                samples will be generated by the Faraday model. For instance,
                if generating samples for January, `n_samples` * 31 will be
                generated and stitched together to produce `n_samples` samples
                with 31 days.
            sampled_features (DataFrame, optional): DataFrame with sampled
                combinations of features. Used to ensure consistency of
                features between different days of the same sample. Can be
                `None` if there are no optional features to take into account.
            randomize_index (bool, optional): Randomize the sample index. To
                ensure that the order of samples combinations of features is
                random.


        Returns:
            pl.DataFrame in wide format with datetime as first columns.
        """

        sampled_features = (
            self._get_sampled_features(dm, n_samples, year=year)
            if sampled_features is None
            else sampled_features
        )
        sample_df = self._generate_sufficient_samples_for_month(
            dm, sampled_features, year, month, n_samples
        )
        result = stitch_samples(sample_df, sampled_features, n_samples)
        result = (
            randomize_index_column(result)
            if randomize_index
            else result.rename({"index": "sample"})
        )

        result = result.sort("sample", "date")

        return result

    def _generate_full_synthetic_year(
        self,
        dm: LCLDataModule,
        year: int,
        n_samples: int = 1,
    ) -> pl.DataFrame:
        """Generate DataFrame Faraday samples for a specific year.

        Samples will be generated with all timesteps for all months in the
        specified year.

        Args:
            dm (LCLDataModule): Data module.
            year (int, optional): Year to use for timestamps.
            n_samples (int): Number of synthetic samples to generate per year.
                This argument specifies the number of stitched-together
                samples. In practice, this means that more samples will be
                generated by the Faraday model. For instance, if generating
                samples for 2024, `n_samples` * 366 samples will be generated
                and stitched together, to produce `n_samples` yearly samples
                with 366 days.

        Returns:
            pl.DataFrame in wide format with datetime as first columns.
        """
        sampled_features = self._get_sampled_features(dm, n_samples, year=year)

        individual_months = [
            self._generate_full_synthetic_month(
                dm=dm,
                year=year,
                month=month,
                n_samples=n_samples,
                sampled_features=sampled_features,
                randomize_index=False,
            )
            for month in tqdm(range(1, 13))
        ]
        # return individual_months
        df = cast(pl.DataFrame, pl.concat(individual_months))
        df = (
            semiwide_to_wide(
                df.select(
                    pl.exclude(
                        *self.required_features, *self.optional_features
                    )
                ),
                date_col="date",
                datetime_name="datetime",
            )
            .with_columns(pl.col("sample").cast(str))
            .transpose(
                column_names="sample",
                include_header=True,
                header_name="datetime",
            )
            .with_columns(pl.col("datetime").str.to_datetime())
        )

        return df

    def _generate_synthetic_daily_samples(
        self,
        dm: LCLDataModule,
        n_samples: int,
        year: int = DEFAULT_YEAR,
        month: int | None = None,
    ) -> Generator[
        Tuple[
            date,
            float,
            float,
            np.typing.NDArray[np.float64],
            np.typing.NDArray[np.float64],
        ],
        None,
        None,
    ]:
        """Generate Faraday samples for a specific month/year combination.

        Samples will be generated with a timestamp that fits the specified
        year and month. If month is not specified, it can be any month.

        Args:
            dm (LCLDataModule): Data module.
            n_samples (int): Number of synthetic daily samples to generate for
                the specified month.
            year (int, optional): Year to use for timestamps.
            month (int, optional): Month (1-based) to use. If generated samples
                do not match the specified month, they will be discarded until
                enough samples are specified that do match.

        Yields:
            Tuple with datetime, month, day_of_week, generated sample values
        """
        # Get dates assigned to weekday/month combination
        dates = date_per_weekday_and_month(year)
        n_batch = n_samples * 100
        n_generated = 0
        feature_index = {f: i for i, f in enumerate(self.model.feature_list)}
        for _ in range(10):  # 1000 times should be enough
            gmm_samples = self.model.sample_gmm(n_batch)

            # Get the features in a numpy array
            feature_samples = np.hstack(
                [
                    gmm_samples["features"][f].numpy()
                    for f in self.model.feature_list
                ]
            )

            # Get the kwh values in a numpy array
            kwh_samples = dm.reconstruct_kwh(gmm_samples["kwh"])
            kwh_samples = torch.clip(kwh_samples, min=0).detach().numpy()

            # Randomly order the generated samples. We get a sample-size-
            # dependent effect otherwise.
            indices = list(range(feature_samples.shape[0]))
            np.random.default_rng().shuffle(indices)

            for i in indices:
                feature_sample = feature_samples[i]
                kwh_sample = kwh_samples[i]
                g_month, dayofweek = (
                    feature_sample[feature_index["month"]],
                    feature_sample[feature_index["dayofweek"]],
                )

                try:
                    if month is None or g_month == month:
                        yield (
                            np.random.choice(
                                np.array(dates[dayofweek][g_month])
                            ),
                            g_month,
                            dayofweek,
                            [
                                feature_sample[j]
                                for f, j in feature_index.items()
                                if f not in ["month", "dayofweek"]
                            ],
                            kwh_sample,
                        )
                        n_generated += 1
                        if n_generated >= n_samples:
                            return

                except Exception as e:
                    logger.warning(f"Skipping sample due to error: {e}")
                    continue

    def _generate_synthetic_sample_df(
        self,
        dm: LCLDataModule,
        n_samples: int,
        year: int = DEFAULT_YEAR,
        month: int | None = None,
    ) -> pl.DataFrame:
        """Generate DataFrame Faraday samples for a month/year combination.

        Samples will be generated with a timestamp that fits the specified
        year and month. If month is not specified, it can be any month.

        Args:
            dm (LCLDataModule): Data module.
            n_samples (int): Number of synthetic daily samples to generate for
                the specified month.
            year (int, optional): Year to use for timestamps.
            month (int, optional): Month (1-based) to use. If generated
                samples do not match the specified month, they will be
                discarded until enough samples are specified that do match.

        Returns:
            DataFrame in wide format with datetime as first columns.
        """
        sample_data = [
            (datetime, m, d, *f, *v)
            for datetime, m, d, f, v in self._generate_synthetic_daily_samples(
                dm, n_samples, year=year, month=month
            )
        ]

        df = pl.DataFrame(
            np.array(sample_data).tolist(),
            schema={"date": pl.Date, "month": int, "dayofweek": int}
            | {f: float for f in self.optional_features}
            | {
                d: float
                for d in [f"{i // 2:02d}{(i % 2) * 30:02d}" for i in range(48)]
            },
            orient="row",
        )

        return df
