name: Test and Lint code
on: [push]
env:
  PYTHONPATH: .

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: "3.11"

      - name: Install Pipenv
        run: |
          pip install pipenv

      - name: Cache virtualenvs
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs/
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Setup Virutual Environment
        run: |
          pipenv sync --dev
          # Need to uninstall and reinstall torch to avoid CUDA error
          pipenv uninstall torch
          pipenv install torch

      - name: Run pytest
        run: pipenv run pytest

      - name: Run precommit
        run: pipenv run pre-commit run --all-files
