name: Test and Lint code
on: [push]
env:
  PYTHONPATH: .

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: "3.11"

      - name: Install Pipenv
        run: |
          pip install pipenv

      - name: Setup Virtual Environment
        run: |
          # Install torch first before installing rest of the dependencies to avoid CUDA error
          pipenv install torch==2.4.0
          pipenv sync --dev

      - name: Run pytest
        run: pipenv run pytest

      - name: Run precommit
        run: pipenv run pre-commit run --all-files
